grandparent(alice,ken).
grandparent(alice,laura).
grandparent(anaGoce,andreasPoca).
grandparent(anaGoce,anisulaProculo).
grandparent(anaGoce,anuclaGondola).
grandparent(anaGoce,anuclaPoca).
grandparent(anaGoce,benedictaGondola).
grandparent(anaGoce,bielauaProculo).
grandparent(anaGoce,bielavaGondola).
grandparent(anaGoce,bielavaPoca).
grandparent(anaGoce,decussaProculo).
grandparent(anaGoce,federicusGondola).
grandparent(anaGoce,petrusProculo).
grandparent(anaGoce,pieroPoca).
grandparent(anaGoce,poloPoca).
grandparent(anaGoce,stephanusGondola).
grandparent(anaGoce,vitaGoce).
grandparent(anisulaGoce,anuclaSorgo).
grandparent(anisulaGoce,stephanusLucaro).
grandparent(anuclaGondola,andreasBona).
grandparent(anuclaGondola,blasiusBona).
grandparent(anuclaGondola,jelussaGoce).
grandparent(anuclaGondola,johannesBona).
grandparent(anuclaGondola,marinusGoce).
grandparent(anuclaGondola,michaelBona).
grandparent(anuclaGondola,michaelProculo).
grandparent(anuclaGondola,natalisProculo).
grandparent(benedictaGondola,anuclaMence).
grandparent(benedictaGondola,francusMence).
grandparent(benedictaGondola,franussaMence).
grandparent(benedictaGondola,mariaMence).
grandparent(benedictaGondola,marinMence).
grandparent(benedictaGondola,nicolinoMence).
grandparent(benedictaGondola,vincentinaMence).
grandparent(benedictusBenkoGondola,antoniusBona).
grandparent(benedictusBenkoGondola,anuclaBona).
grandparent(benedictusBenkoGondola,benedictusGondola).
grandparent(benedictusBenkoGondola,bielceGondola).
grandparent(benedictusBenkoGondola,catharinaBona).
grandparent(benedictusBenkoGondola,couanGondola).
grandparent(benedictusBenkoGondola,federicusGondola).
grandparent(benedictusBenkoGondola,franchusBasilio).
grandparent(benedictusBenkoGondola,lignussaMence).
grandparent(benedictusBenkoGondola,mariaBasilio).
grandparent(benedictusBenkoGondola,mariaGondola).
grandparent(benedictusBenkoGondola,marinusGondola).
grandparent(benedictusBenkoGondola,matchoMence).
grandparent(benedictusBenkoGondola,mirussaBasilio).
grandparent(benedictusBenkoGondola,nicolausGondola).
grandparent(benedictusBenkoGondola,pauchoGondola).
grandparent(benedictusBenkoGondola,pervulaGondola).
grandparent(benedictusBenkoGondola,pieroBona).
grandparent(benedictusBenkoGondola,radulaMence).
grandparent(bielavaPoca,bartholusCaboga).
grandparent(bielavaPoca,catharinaCaboga).
grandparent(bielavaPoca,christophorusCaboga).
grandparent(bielavaPoca,fiochaCaboga).
grandparent(bielavaPoca,franciscusCaboga).
grandparent(bielavaPoca,johannesGeorgio).
grandparent(bielavaPoca,juniusCaboga).
grandparent(bielavaPoca,marussaCaboga).
grandparent(bielavaPoca,michaelCaboga).
grandparent(bielavaPoca,nicolausCaboga).
grandparent(bielavaPoca,nicolausGeorgio).
grandparent(bielavaPoca,nicoletaCaboga).
grandparent(bielavaPoca,petrusCaboga).
grandparent(bielavaPoca,sigismundGeorgio).
grandparent(bielavaPoca,ziuanaCaboga).
grandparent(bob,ken).
grandparent(bob,laura).
grandparent(clemensGoce,johannesGoce).
grandparent(damianusDamianoSorgo,aeliusZrieva).
grandparent(damianusDamianoSorgo,catharinaBona).
grandparent(damianusDamianoSorgo,franussaSorgo).
grandparent(damianusDamianoSorgo,jelussaZrieva).
grandparent(damianusDamianoSorgo,marussaSorgo).
grandparent(damianusDamianoSorgo,michaelPoca).
grandparent(damianusDamianoSorgo,natalisSorgo).
grandparent(damianusDamianoSorgo,nicolaPoca).
grandparent(damianusDamianoSorgo,orsulaZrieva).
grandparent(damianusDamianoSorgo,pasquaZrieva).
grandparent(damianusDamianoSorgo,petrusSorgo).
grandparent(damianusDamianoSorgo,pirchoSorgo).
grandparent(damianusDamianoSorgo,stipechoPoca).
grandparent(damianusDamianoSorgo,troianZrieva).
grandparent(damianusDamianoSorgo,vladislavSorgo).
grandparent(decussaProculo,aeliusZrieva).
grandparent(decussaProculo,catharinaBona).
grandparent(decussaProculo,franussaSorgo).
grandparent(decussaProculo,jelussaZrieva).
grandparent(decussaProculo,marussaSorgo).
grandparent(decussaProculo,michaelPoca).
grandparent(decussaProculo,natalisSorgo).
grandparent(decussaProculo,nicolaPoca).
grandparent(decussaProculo,orsulaZrieva).
grandparent(decussaProculo,pasquaZrieva).
grandparent(decussaProculo,petrusSorgo).
grandparent(decussaProculo,pirchoSorgo).
grandparent(decussaProculo,stipechoPoca).
grandparent(decussaProculo,troianZrieva).
grandparent(decussaProculo,vladislavSorgo).
grandparent(federicusGondola,anisulaProculo).
grandparent(federicusGondola,benedictusBenkoGondola).
grandparent(federicusGondola,benedictusGondola).
grandparent(federicusGondola,bielauaProculo).
grandparent(federicusGondola,bielceGondola).
grandparent(federicusGondola,blasiusGondola).
grandparent(federicusGondola,couanGondola).
grandparent(federicusGondola,decussaProculo).
grandparent(federicusGondola,federicoGondola).
grandparent(federicusGondola,franussaProculo).
grandparent(federicusGondola,jacobusProculo).
grandparent(federicusGondola,jacussaProculo).
grandparent(federicusGondola,margaritaGondola).
grandparent(federicusGondola,mariaGondola).
grandparent(federicusGondola,marincoGondola).
grandparent(federicusGondola,marinusGondola).
grandparent(federicusGondola,marussaGoce).
grandparent(federicusGondola,michaelProculo).
grandparent(federicusGondola,nicolausGondola).
grandparent(federicusGondola,orsulaGondola).
grandparent(federicusGondola,pauchoGondola).
grandparent(federicusGondola,pervulaGondola).
grandparent(federicusGondola,petrusProculo).
grandparent(federicusGondola,vitaGoce).
grandparent(franussaSorgo,aloisioBona).
grandparent(franussaSorgo,michielBona).
grandparent(franussaSorgo,stephanusGoce).
grandparent(franussaZrieva,federicusGondola).
grandparent(franussaZrieva,margaritaGondola).
grandparent(franussaZrieva,orsulaGondola).
grandparent(gaiussaZamagna,franussaLucaro).
grandparent(gaiussaZamagna,jelussaLucaro).
grandparent(gaiussaZamagna,nicolaLucaro).
grandparent(gaiussaZamagna,pasqualisSorgo).
grandparent(gaiussaZamagna,petrusLucaro).
grandparent(gaiussaZamagna,petrusSorgo).
grandparent(gaiussaZamagna,stephanusLucaro).
grandparent(georgiusGoce,jacobusCaboga).
grandparent(jacobusProculo,aloisusGoce).
grandparent(jacobusProculo,christinaGoce).
grandparent(jacobusProculo,gratiaGoce).
grandparent(jacobusProculo,jacomoGoce).
grandparent(jacobusProculo,johanesGoce).
grandparent(jacobusProculo,marinoGoce).
grandparent(jacobusProculo,michaelProculo).
grandparent(jacobusProculo,petrusProculo).
grandparent(jacobusProculo,vechiaGoce).
grandparent(jacobusProculo,veneraGoce).
grandparent(jelussaGoce,franaBabalio).
grandparent(jelussaGoce,franoBabalio).
grandparent(jelussaGoce,maraBabalio).
grandparent(jelussaGoce,marinBabalio).
grandparent(jelussaGoce,nichaBabalio).
grandparent(jelussaGoce,paulaBabalio).
grandparent(jelussaGoce,saboBabalio).
grandparent(jelussaGoce,sigismundoBabalio).
grandparent(jelussaGoce,stephanBabalio).
grandparent(jelussaZrieva,aloisioGoce).
grandparent(jelussaZrieva,christinaGoce).
grandparent(jelussaZrieva,orsatusGoce).
grandparent(johanaPoca,anuclaPoca).
grandparent(johanaPoca,blasiusRagnina).
grandparent(johanaPoca,dobrulizaRagnina).
grandparent(johanaPoca,gaiussaGeorgio).
grandparent(johanaPoca,johanaBona).
grandparent(johanaPoca,johanaGeorgio).
grandparent(johanaPoca,mariaRagnina).
grandparent(johanaPoca,marinusGoce).
grandparent(johanaPoca,marussaGeorgio).
grandparent(johanaPoca,nicolausGoce).
grandparent(johanaPoca,paulusPoca).
grandparent(johanaPoca,zupanusBona).
grandparent(johannesGondola,federicusGondola).
grandparent(johannesGondola,margaritaGondola).
grandparent(johannesGondola,orsulaGondola).
grandparent(juniusSorgo,anuclaSorgo).
grandparent(juniusSorgo,benedictaSorgo).
grandparent(juniusSorgo,francischaSorgo).
grandparent(juniusSorgo,franussaLucaro).
grandparent(juniusSorgo,jelussaLucaro).
grandparent(juniusSorgo,katharinaSorgo).
grandparent(juniusSorgo,lignussaSorgo).
grandparent(juniusSorgo,marussaSorgo).
grandparent(juniusSorgo,nicolaLucaro).
grandparent(juniusSorgo,pasqualisSorgo).
grandparent(juniusSorgo,petrusLucaro).
grandparent(juniusSorgo,petrusSorgo).
grandparent(juniusSorgo,stephanusLucaro).
grandparent(katharinaSorgo,aeliusZrieva).
grandparent(katharinaSorgo,catharinaBona).
grandparent(katharinaSorgo,jelussaZrieva).
grandparent(katharinaSorgo,michaelPoca).
grandparent(katharinaSorgo,nicolaPoca).
grandparent(katharinaSorgo,orsulaZrieva).
grandparent(katharinaSorgo,pasquaZrieva).
grandparent(katharinaSorgo,stipechoPoca).
grandparent(katharinaSorgo,troianZrieva).
grandparent(lampreZrieva,lampricaZrieva).
grandparent(lampreZrieva,mariaZrieva).
grandparent(lampreZrieva,marincusZrieva).
grandparent(lampreZrieva,marinusGoce).
grandparent(lampreZrieva,pasqualisZrieva).
grandparent(lampreZrieva,petronellaZrieva).
grandparent(laurentiusSorgo,aeliusZrieva).
grandparent(laurentiusSorgo,catharinaBona).
grandparent(laurentiusSorgo,jelussaZrieva).
grandparent(laurentiusSorgo,michaelPoca).
grandparent(laurentiusSorgo,nicolaPoca).
grandparent(laurentiusSorgo,orsulaZrieva).
grandparent(laurentiusSorgo,pasquaZrieva).
grandparent(laurentiusSorgo,stipechoPoca).
grandparent(laurentiusSorgo,troianZrieva).
grandparent(lignussaMence,aloisioGoce).
grandparent(lignussaMence,christinaGoce).
grandparent(lignussaMence,michaelBabalio).
grandparent(lignussaMence,orsatusGoce).
grandparent(lignussaMence,sebastianBabalio).
grandparent(lignussaSorgo,aeliusZrieva).
grandparent(lignussaSorgo,aloisioGoce).
grandparent(lignussaSorgo,catharinaBona).
grandparent(lignussaSorgo,christinaGoce).
grandparent(lignussaSorgo,jelussaZrieva).
grandparent(lignussaSorgo,michaelPoca).
grandparent(lignussaSorgo,nicolaPoca).
grandparent(lignussaSorgo,orsatusGoce).
grandparent(lignussaSorgo,orsulaZrieva).
grandparent(lignussaSorgo,pasquaZrieva).
grandparent(lignussaSorgo,stipechoPoca).
grandparent(lignussaSorgo,troianZrieva).
grandparent(maraGoce,aeliusZrieva).
grandparent(maraGoce,catharinaBona).
grandparent(maraGoce,franussaSorgo).
grandparent(maraGoce,jelussaZrieva).
grandparent(maraGoce,marimLucaro).
grandparent(maraGoce,marussaSorgo).
grandparent(maraGoce,michaelPoca).
grandparent(maraGoce,natalisSorgo).
grandparent(maraGoce,nicolaCaboga).
grandparent(maraGoce,nicolaPoca).
grandparent(maraGoce,orsulaZrieva).
grandparent(maraGoce,pasquaCaboga).
grandparent(maraGoce,pasqualisLucaro).
grandparent(maraGoce,pasqualisSorgo).
grandparent(maraGoce,pasquaZrieva).
grandparent(maraGoce,petrusSorgo).
grandparent(maraGoce,pirchoSorgo).
grandparent(maraGoce,stipechoPoca).
grandparent(maraGoce,troianZrieva).
grandparent(maraGoce,vladislavSorgo).
grandparent(margarita,anuclaPoca).
grandparent(margarita,federicusGoce).
grandparent(margarita,nicoletaResti).
grandparent(margarita,pandulphusPoca).
grandparent(margarita,paulusGoce).
grandparent(margarita,petronellaPoca).
grandparent(margaritaProculo,michaelProculo).
grandparent(margaritaProculo,natalisProculo).
grandparent(margarita,raynaldusPoca).
grandparent(mariaGondola,annaBona).
grandparent(mariaGondola,anuclaPoca).
grandparent(mariaGondola,bartholusCaboga).
grandparent(mariaGondola,benedictaBona).
grandparent(mariaGondola,carolusPoca).
grandparent(mariaGondola,catharinaCaboga).
grandparent(mariaGondola,catharinaPoca).
grandparent(mariaGondola,christophorusCaboga).
grandparent(mariaGondola,federicusGoce).
grandparent(mariaGondola,fiochaBona).
grandparent(mariaGondola,fiochaCaboga).
grandparent(mariaGondola,franciscusCaboga).
grandparent(mariaGondola,franussaBona).
grandparent(mariaGondola,juniusCaboga).
grandparent(mariaGondola,magdalenaBona).
grandparent(mariaGondola,marinusBona).
grandparent(mariaGondola,marussaBona).
grandparent(mariaGondola,marussaCaboga).
grandparent(mariaGondola,marussaPoca).
grandparent(mariaGondola,michaelBona).
grandparent(mariaGondola,michaelCaboga).
grandparent(mariaGondola,michaelPoca).
grandparent(mariaGondola,nicolaPoca).
grandparent(mariaGondola,nicolausBona).
grandparent(mariaGondola,nicolausCaboga).
grandparent(mariaGondola,nicoletaBona).
grandparent(mariaGondola,nicoletaCaboga).
grandparent(mariaGondola,nicoletaPoca).
grandparent(mariaGondola,nicoletaResti).
grandparent(mariaGondola,pandulphusPoca).
grandparent(mariaGondola,paulusGoce).
grandparent(mariaGondola,petrusCaboga).
grandparent(mariaGondola,secundusBona).
grandparent(mariaGondola,simonPoca).
grandparent(mariaGondola,stipechoPoca).
grandparent(mariaGondola,thomasoPoca).
grandparent(mariaGondola,ziuanaCaboga).
grandparent(marinusBona,federicusGoce).
grandparent(marinusBona,nicoletaResti).
grandparent(marinusBona,paulusGoce).
grandparent(marinusGoce,aloisioBona).
grandparent(marinusGoce,michielBona).
grandparent(marinusGoce,stephanusGoce).
grandparent(marinusGondola,bielavaGondola).
grandparent(marinusGondola,johannesGondola).
grandparent(marinusGondola,lampricaZrieva).
grandparent(marinusGondola,marincusZrieva).
grandparent(marinusGondola,pasqualisZrieva).
grandparent(marinusGondola,pervulaGondola).
grandparent(marinusGondola,petrusGondola).
grandparent(marinusGondola,stephanusGondola).
grandparent(martinusGoce,aloisioGoce).
grandparent(martinusGoce,christinaGoce).
grandparent(martinusGoce,orsatusGoce).
grandparent(marussaSorgo,andreasPoca).
grandparent(marussaSorgo,anuclaPoca).
grandparent(marussaSorgo,bielavaPoca).
grandparent(marussaSorgo,franussaPoca).
grandparent(marussaSorgo,giovanniPoca).
grandparent(marussaSorgo,johanaPoca).
grandparent(marussaSorgo,lampricaZrieva).
grandparent(marussaSorgo,mariaZrieva).
grandparent(marussaSorgo,marincusZrieva).
grandparent(marussaSorgo,marinusGoce).
grandparent(marussaSorgo,maroePoca).
grandparent(marussaSorgo,michaelPoca).
grandparent(marussaSorgo,nicoleticaPoca).
grandparent(marussaSorgo,pasqualisZrieva).
grandparent(marussaSorgo,petronellaZrieva).
grandparent(marussaSorgo,pieroPoca).
grandparent(marussaSorgo,poloPoca).
grandparent(michaelBona,federicusGoce).
grandparent(michaelBona,nicoletaResti).
grandparent(michaelBona,paulusGoce).
grandparent(michielMence,andreasBona).
grandparent(michielMence,blasiusBona).
grandparent(michielMence,jelussaGoce).
grandparent(michielMence,johannesBona).
grandparent(michielMence,marinusGoce).
grandparent(michielMence,michaelBona).
grandparent(michielMence,michaelProculo).
grandparent(michielMence,natalisProculo).
grandparent(mirussaBincola,bielavaGondola).
grandparent(mirussaBincola,johannesGondola).
grandparent(mirussaBincola,lampricaZrieva).
grandparent(mirussaBincola,marincusZrieva).
grandparent(mirussaBincola,marinusGondola).
grandparent(mirussaBincola,pasqualisZrieva).
grandparent(mirussaBincola,pervulaGondola).
grandparent(mirussaBincola,petrusGondola).
grandparent(mirussaBincola,stephanusGondola).
grandparent(nalcusProculo,antolinaProculo).
grandparent(nalcusProculo,dobruschoBuchia).
grandparent(nalcusProculo,hieronymusBuchia).
grandparent(nalcusProculo,jacobusSorgo).
grandparent(nalcusProculo,johannesBuchia).
grandparent(nalcusProculo,juniusSorgo).
grandparent(nalcusProculo,lignussaSorgo).
grandparent(nalcusProculo,marinusSorgo).
grandparent(nalcusProculo,marussaSorgo).
grandparent(nalcusProculo,michaelProculo).
grandparent(nalcusProculo,natalisBuchia).
grandparent(nalcusProculo,natalisProculo).
grandparent(nalcusProculo,natalisSorgo).
grandparent(nalcusProculo,natalProculo).
grandparent(nalcusProculo,nicolausProculo).
grandparent(nalcusProculo,nicoletaProculo).
grandparent(nalcusProculo,pasqualSorgo).
grandparent(nalcusProculo,pervolaSorgo).
grandparent(nalcusProculo,pervulaProculo).
grandparent(nicolaBona,anuclaPoca).
grandparent(nicolaBona,paulusPoca).
grandparent(nicolaPoca,annaBona).
grandparent(nicolaPoca,anuclaPoca).
grandparent(nicolaPoca,bartholusCaboga).
grandparent(nicolaPoca,benedictaBona).
grandparent(nicolaPoca,carolusPoca).
grandparent(nicolaPoca,catharinaCaboga).
grandparent(nicolaPoca,catharinaPoca).
grandparent(nicolaPoca,christophorusCaboga).
grandparent(nicolaPoca,federicusGoce).
grandparent(nicolaPoca,fiochaBona).
grandparent(nicolaPoca,fiochaCaboga).
grandparent(nicolaPoca,franciscusCaboga).
grandparent(nicolaPoca,franussaBona).
grandparent(nicolaPoca,juniusCaboga).
grandparent(nicolaPoca,magdalenaBona).
grandparent(nicolaPoca,marinusBona).
grandparent(nicolaPoca,marussaBona).
grandparent(nicolaPoca,marussaCaboga).
grandparent(nicolaPoca,marussaPoca).
grandparent(nicolaPoca,michaelBona).
grandparent(nicolaPoca,michaelCaboga).
grandparent(nicolaPoca,michaelPoca).
grandparent(nicolaPoca,nicolausBona).
grandparent(nicolaPoca,nicolausCaboga).
grandparent(nicolaPoca,nicoletaBona).
grandparent(nicolaPoca,nicoletaCaboga).
grandparent(nicolaPoca,nicoletaPoca).
grandparent(nicolaPoca,nicoletaResti).
grandparent(nicolaPoca,pandulphusPoca).
grandparent(nicolaPoca,paulusGoce).
grandparent(nicolaPoca,petrusCaboga).
grandparent(nicolaPoca,secundusBona).
grandparent(nicolaPoca,simonPoca).
grandparent(nicolaPoca,stipechoPoca).
grandparent(nicolaPoca,thomasoPoca).
grandparent(nicolaPoca,ziuanaCaboga).
grandparent(nicolausBona,franchaMence).
grandparent(nicolausBona,maraMence).
grandparent(nicolausBona,marinusMence).
grandparent(nicolausBona,nichaMence).
grandparent(nicolausBona,nicolausMence).
grandparent(nicolausBona,pasqualisMence).
grandparent(nicolausBona,troianusMence).
grandparent(nicolausCaboga,bartholusCaboga).
grandparent(nicolausCaboga,catharinaCaboga).
grandparent(nicolausCaboga,christophorusCaboga).
grandparent(nicolausCaboga,fiochaCaboga).
grandparent(nicolausCaboga,franciscusCaboga).
grandparent(nicolausCaboga,johannesGeorgio).
grandparent(nicolausCaboga,juniusCaboga).
grandparent(nicolausCaboga,marussaCaboga).
grandparent(nicolausCaboga,michaelCaboga).
grandparent(nicolausCaboga,nicolausGeorgio).
grandparent(nicolausCaboga,nicoletaCaboga).
grandparent(nicolausCaboga,petrusCaboga).
grandparent(nicolausCaboga,sigismundGeorgio).
grandparent(nicolausCaboga,ziuanaCaboga).
grandparent(nicolausProculo,michaelProculo).
grandparent(nicolausProculo,natalisProculo).
grandparent(nicoletaBona,aloisioGoce).
grandparent(nicoletaBona,christinaGoce).
grandparent(nicoletaBona,orsatusGoce).
grandparent(nicoletaGrede,franchaMence).
grandparent(nicoletaGrede,maraMence).
grandparent(nicoletaGrede,marinusMence).
grandparent(nicoletaGrede,nichaMence).
grandparent(nicoletaGrede,nicolausMence).
grandparent(nicoletaGrede,pasqualisMence).
grandparent(nicoletaGrede,troianusMence).
grandparent(nicolinusBasilio,anuclaMence).
grandparent(nicolinusBasilio,francusMence).
grandparent(nicolinusBasilio,franussaMence).
grandparent(nicolinusBasilio,mariaMence).
grandparent(nicolinusBasilio,marinMence).
grandparent(nicolinusBasilio,nicolinoMence).
grandparent(nicolinusBasilio,vincentinaMence).
grandparent(orsatusSorgo,aeliusZrieva).
grandparent(orsatusSorgo,aloisioGoce).
grandparent(orsatusSorgo,catharinaBona).
grandparent(orsatusSorgo,christinaGoce).
grandparent(orsatusSorgo,jelussaZrieva).
grandparent(orsatusSorgo,michaelPoca).
grandparent(orsatusSorgo,nicolaPoca).
grandparent(orsatusSorgo,orsatusGoce).
grandparent(orsatusSorgo,orsulaZrieva).
grandparent(orsatusSorgo,pasquaZrieva).
grandparent(orsatusSorgo,stipechoPoca).
grandparent(orsatusSorgo,troianZrieva).
grandparent(orsulaGeorgio,anisulaProculo).
grandparent(orsulaGeorgio,benedictusBenkoGondola).
grandparent(orsulaGeorgio,benedictusGondola).
grandparent(orsulaGeorgio,bielauaProculo).
grandparent(orsulaGeorgio,bielceGondola).
grandparent(orsulaGeorgio,blasiusGondola).
grandparent(orsulaGeorgio,couanGondola).
grandparent(orsulaGeorgio,decussaProculo).
grandparent(orsulaGeorgio,federicoGondola).
grandparent(orsulaGeorgio,federicusGondola).
grandparent(orsulaGeorgio,franussaProculo).
grandparent(orsulaGeorgio,jacobusProculo).
grandparent(orsulaGeorgio,jacussaProculo).
grandparent(orsulaGeorgio,margaritaGondola).
grandparent(orsulaGeorgio,mariaGondola).
grandparent(orsulaGeorgio,marincoGondola).
grandparent(orsulaGeorgio,marinusGondola).
grandparent(orsulaGeorgio,marussaGoce).
grandparent(orsulaGeorgio,michaelProculo).
grandparent(orsulaGeorgio,nicolausGondola).
grandparent(orsulaGeorgio,orsulaGondola).
grandparent(orsulaGeorgio,pauchoGondola).
grandparent(orsulaGeorgio,pervulaGondola).
grandparent(orsulaGeorgio,petrusProculo).
grandparent(orsulaGeorgio,vitaGoce).
grandparent(paladinoGoce,aloisioGoce).
grandparent(paladinoGoce,christinaGoce).
grandparent(paladinoGoce,orsatusGoce).
grandparent(pandulphusPoca,anuclaPoca).
grandparent(pandulphusPoca,federicusGoce).
grandparent(pandulphusPoca,nicoletaResti).
grandparent(pandulphusPoca,paulusGoce).
grandparent(pandulphusPoca,petronellaPoca).
grandparent(pandulphusPoca,raynaldusPoca).
grandparent(paula,franussaLucaro).
grandparent(paula,jelussaLucaro).
grandparent(paula,nicolaLucaro).
grandparent(paula,pasqualisSorgo).
grandparent(paula,petrusLucaro).
grandparent(paula,petrusSorgo).
grandparent(paula,poloGoce).
grandparent(paula,stephanusGoce).
grandparent(paula,stephanusLucaro).
grandparent(pervulaGondola,antolinaProculo).
grandparent(pervulaGondola,dobruschoBuchia).
grandparent(pervulaGondola,hieronymusBuchia).
grandparent(pervulaGondola,jacobusSorgo).
grandparent(pervulaGondola,johannesBuchia).
grandparent(pervulaGondola,johannesGoce).
grandparent(pervulaGondola,juniusSorgo).
grandparent(pervulaGondola,lignussaSorgo).
grandparent(pervulaGondola,marinusSorgo).
grandparent(pervulaGondola,marussaSorgo).
grandparent(pervulaGondola,michaelProculo).
grandparent(pervulaGondola,natalisBuchia).
grandparent(pervulaGondola,natalisProculo).
grandparent(pervulaGondola,natalisSorgo).
grandparent(pervulaGondola,natalProculo).
grandparent(pervulaGondola,nicolausProculo).
grandparent(pervulaGondola,nicoletaProculo).
grandparent(pervulaGondola,pasqualSorgo).
grandparent(pervulaGondola,pervolaSorgo).
grandparent(pervulaGondola,pervulaProculo).
grandparent(pervulaProculo,jacobusCaboga).
grandparent(petronellaCaboga,anuclaPoca).
grandparent(petronellaCaboga,federicusGoce).
grandparent(petronellaCaboga,nicoletaResti).
grandparent(petronellaCaboga,pandulphusPoca).
grandparent(petronellaCaboga,paulusGoce).
grandparent(petronellaCaboga,petronellaPoca).
grandparent(petronellaCaboga,raynaldusPoca).
grandparent(petrusGondola,andreasPoca).
grandparent(petrusGondola,anisulaProculo).
grandparent(petrusGondola,anuclaGondola).
grandparent(petrusGondola,anuclaPoca).
grandparent(petrusGondola,benedictaGondola).
grandparent(petrusGondola,bielauaProculo).
grandparent(petrusGondola,bielavaGondola).
grandparent(petrusGondola,bielavaPoca).
grandparent(petrusGondola,decussaProculo).
grandparent(petrusGondola,federicusGondola).
grandparent(petrusGondola,franussaPoca).
grandparent(petrusGondola,franussaProculo).
grandparent(petrusGondola,giovanniPoca).
grandparent(petrusGondola,jacobusProculo).
grandparent(petrusGondola,jacussaProculo).
grandparent(petrusGondola,jelussaGondola).
grandparent(petrusGondola,johanaPoca).
grandparent(petrusGondola,johannesGondola).
grandparent(petrusGondola,madussaGondola).
grandparent(petrusGondola,margaritaGondola).
grandparent(petrusGondola,marinusGondola).
grandparent(petrusGondola,maroePoca).
grandparent(petrusGondola,marussaGoce).
grandparent(petrusGondola,michaelPoca).
grandparent(petrusGondola,michaelProculo).
grandparent(petrusGondola,nicoleticaPoca).
grandparent(petrusGondola,orsulaGondola).
grandparent(petrusGondola,pervulaGondola).
grandparent(petrusGondola,petrusProculo).
grandparent(petrusGondola,pieroPoca).
grandparent(petrusGondola,poloPoca).
grandparent(petrusGondola,stephanusGondola).
grandparent(petrusGondola,vitaGoce).
grandparent(petrusSorgo,franussaLucaro).
grandparent(petrusSorgo,jelussaLucaro).
grandparent(petrusSorgo,nicolaLucaro).
grandparent(petrusSorgo,pasqualisSorgo).
grandparent(petrusSorgo,petrusLucaro).
grandparent(petrusSorgo,poloGoce).
grandparent(petrusSorgo,stephanusGoce).
grandparent(petrusSorgo,stephanusLucaro).
grandparent(pieroPoca,andreasPoca).
grandparent(pieroPoca,anuclaPoca).
grandparent(pieroPoca,bielavaPoca).
grandparent(pieroPoca,franussaPoca).
grandparent(pieroPoca,giovanniPoca).
grandparent(pieroPoca,johanaPoca).
grandparent(pieroPoca,maroePoca).
grandparent(pieroPoca,michaelPoca).
grandparent(pieroPoca,nicoleticaPoca).
grandparent(pieroPoca,poloPoca).
grandparent(poloPoca,anuclaPoca).
grandparent(poloPoca,federicusGoce).
grandparent(poloPoca,nicoletaResti).
grandparent(poloPoca,pandulphusPoca).
grandparent(poloPoca,paulusGoce).
grandparent(poloPoca,petronellaPoca).
grandparent(poloPoca,raynaldusPoca).
grandparent(radeGoce,antoniusBona).
grandparent(radeGoce,anuclaBona).
grandparent(radeGoce,benedictusBenkoGondola).
grandparent(radeGoce,benedictusGondola).
grandparent(radeGoce,bielceGondola).
grandparent(radeGoce,catharinaBona).
grandparent(radeGoce,matchoMence).
grandparent(radeGoce,mirussaBasilio).
grandparent(radeGoce,nicolausGondola).
grandparent(radeGoce,pauchoGondola).
grandparent(radeGoce,pervulaGondola).
grandparent(radeGoce,pieroBona).
grandparent(radeGoce,radulaMence).
grandparent(radulaMence,anuclaPoca).
grandparent(radulaMence,paulusPoca).
grandparent(raphaelGoce,aloisioGoce).
grandparent(raphaelGoce,christinaGoce).
grandparent(raphaelGoce,michaelBabalio).
grandparent(raphaelGoce,orsatusGoce).
grandparent(raphaelGoce,sebastianBabalio).
grandparent(savinusBabalio,franaBabalio).
grandparent(savinusBabalio,franoBabalio).
grandparent(savinusBabalio,maraBabalio).
grandparent(savinusBabalio,marinBabalio).
grandparent(savinusBabalio,sigismundoBabalio).
grandparent(savinusBabalio,stephanBabalio).
grandparent(vechiaGeorgio,aloisusGoce).
grandparent(vechiaGeorgio,christinaGoce).
grandparent(vechiaGeorgio,gratiaGoce).
grandparent(vechiaGeorgio,jacomoGoce).
grandparent(vechiaGeorgio,johanesGoce).
grandparent(vechiaGeorgio,marinoGoce).
grandparent(vechiaGeorgio,michaelProculo).
grandparent(vechiaGeorgio,petrusProculo).
grandparent(vechiaGeorgio,vechiaGoce).
grandparent(vechiaGeorgio,veneraGoce).
grandparent(vladislavSorgo,aeliusZrieva).
grandparent(vladislavSorgo,catharinaBona).
grandparent(vladislavSorgo,franussaSorgo).
grandparent(vladislavSorgo,jelussaZrieva).
grandparent(vladislavSorgo,marimLucaro).
grandparent(vladislavSorgo,marussaSorgo).
grandparent(vladislavSorgo,michaelPoca).
grandparent(vladislavSorgo,natalisSorgo).
grandparent(vladislavSorgo,nicolaCaboga).
grandparent(vladislavSorgo,troianZrieva).
grandparent(zupanBona,anuclaPoca).
grandparent(zupanBona,blasiusRagnina).
grandparent(zupanBona,dobrulizaRagnina).
grandparent(zupanBona,gaiussaGeorgio).
grandparent(zupanBona,johanaBona).
grandparent(zupanBona,johanaGeorgio).
grandparent(zupanBona,mariaRagnina).
grandparent(zupanBona,marinusGoce).
grandparent(zupanBona,marussaGeorgio).
grandparent(zupanBona,nicolausGoce).
grandparent(zupanBona,paulusPoca).
grandparent(zupanBona,zupanusBona).
